name: sync-files

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  sync-files:
    runs-on: ubuntu-latest
    steps:
      - name: Run sync-files
        uses: autowarefoundation/autoware-github-actions/sync-files@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr-labels: |
            bot
            sync-files
          auto-merge-method: squash
